// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMU9ZqqHQ5N0mASVIZ46CWwwWOFu_gyA',
    appId: '1:1078898521529:web:2adf20e1fc5a97a538f268',
    messagingSenderId: '1078898521529',
    projectId: 'e-commerce-47b48',
    authDomain: 'e-commerce-47b48.firebaseapp.com',
    storageBucket: 'e-commerce-47b48.firebasestorage.app',
    measurementId: 'G-V91QZGJM7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtIXZFLdGvQZ9ekkAs2TMnmKivu7JVZ0',
    appId: '1:1078898521529:android:bcfc2c6f7b7c641138f268',
    messagingSenderId: '1078898521529',
    projectId: 'e-commerce-47b48',
    storageBucket: 'e-commerce-47b48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSK4gCWKhQ12-MFtpS4lWCMLhtwJemShM',
    appId: '1:1078898521529:ios:7cfa5878b098c29a38f268',
    messagingSenderId: '1078898521529',
    projectId: 'e-commerce-47b48',
    storageBucket: 'e-commerce-47b48.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSK4gCWKhQ12-MFtpS4lWCMLhtwJemShM',
    appId: '1:1078898521529:ios:7cfa5878b098c29a38f268',
    messagingSenderId: '1078898521529',
    projectId: 'e-commerce-47b48',
    storageBucket: 'e-commerce-47b48.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtMU9ZqqHQ5N0mASVIZ46CWwwWOFu_gyA',
    appId: '1:1078898521529:web:438e68b7424feb5238f268',
    messagingSenderId: '1078898521529',
    projectId: 'e-commerce-47b48',
    authDomain: 'e-commerce-47b48.firebaseapp.com',
    storageBucket: 'e-commerce-47b48.firebasestorage.app',
    measurementId: 'G-QDJ25M1G8P',
  );

}